export type DirectorySheet = "MENA Ecommerce" | "Global Ecommerce" | "Remote-First Tech";

export interface DirectoryCompany {
  id: string;
  sheet: DirectorySheet;
  company: string;
  hqCountry: string;
  remotePolicy: string;
  careersPage: string;
  hrEmail: string;
  notes: string;
}

// Extracted directly from ecommerce_qa_job_database.xlsx (MENA Ecommerce, Global
// Ecommerce, and Remote-First Tech tabs) — company/careers-page directory, not
// individual verified job postings.
export const companyDirectory: DirectoryCompany[] = [
  {
    id: "amazon-ae",
    sheet: "MENA Ecommerce",
    company: "Amazon.ae",
    hqCountry: "UAE/Global",
    remotePolicy: "Onsite/Hybrid (varies)",
    careersPage: "https://www.amazon.jobs",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Posted on global Amazon.jobs; filter by UAE or Remote.",
  },
  {
    id: "noon",
    sheet: "MENA Ecommerce",
    company: "noon",
    hqCountry: "UAE",
    remotePolicy: "Onsite/Hybrid",
    careersPage: "https://careers.noon.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "You have direct prior QA leadership experience here.",
  },
  {
    id: "namshi",
    sheet: "MENA Ecommerce",
    company: "Namshi",
    hqCountry: "UAE",
    remotePolicy: "Onsite/Hybrid",
    careersPage: "https://namshi.com/uae-en/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Al-Futtaim/Emaar group fashion e-commerce.",
  },
  {
    id: "ounass",
    sheet: "MENA Ecommerce",
    company: "Ounass",
    hqCountry: "UAE",
    remotePolicy: "Onsite",
    careersPage: "https://www.ounass.ae/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Al Tayer Group luxury e-commerce.",
  },
  {
    id: "sharaf-dg",
    sheet: "MENA Ecommerce",
    company: "Sharaf DG",
    hqCountry: "UAE",
    remotePolicy: "Onsite",
    careersPage: "https://www.sharafdg.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Electronics retail + e-commerce.",
  },
  {
    id: "carrefour-uae-majid-al-futtaim",
    sheet: "MENA Ecommerce",
    company: "Carrefour UAE (Majid Al Futtaim)",
    hqCountry: "UAE",
    remotePolicy: "Onsite/Hybrid",
    careersPage: "https://careers.majidalfuttaim.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Grocery/retail e-commerce group.",
  },
  {
    id: "talabat",
    sheet: "MENA Ecommerce",
    company: "Talabat",
    hqCountry: "UAE (Delivery Hero group)",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.talabat.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Part of Delivery Hero; regional tech hub.",
  },
  {
    id: "instashop",
    sheet: "MENA Ecommerce",
    company: "InstaShop",
    hqCountry: "UAE (Delivery Hero group)",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.talabat.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Shares hiring with Talabat/Delivery Hero.",
  },
  {
    id: "letstango",
    sheet: "MENA Ecommerce",
    company: "LetsTango",
    hqCountry: "UAE",
    remotePolicy: "Onsite",
    careersPage: "https://www.letstango.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Smaller team; LinkedIn outreach recommended.",
  },
  {
    id: "greenhonchos",
    sheet: "MENA Ecommerce",
    company: "GreenHonchos",
    hqCountry: "UAE",
    remotePolicy: "Onsite",
    careersPage: "Check LinkedIn company page",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "No dedicated careers portal found.",
  },
  {
    id: "basharacare",
    sheet: "MENA Ecommerce",
    company: "Basharacare",
    hqCountry: "UAE",
    remotePolicy: "Onsite",
    careersPage: "https://www.basharacare.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Healthcare/pharmacy e-commerce.",
  },
  {
    id: "souq-legacy-now-amazon-ae",
    sheet: "MENA Ecommerce",
    company: "Souq (legacy, now Amazon.ae)",
    hqCountry: "UAE",
    remotePolicy: "N/A",
    careersPage: "https://www.amazon.jobs",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Fully absorbed into Amazon.ae.",
  },
  {
    id: "6thstreet-com",
    sheet: "MENA Ecommerce",
    company: "6thStreet.com",
    hqCountry: "UAE (Apparel Group)",
    remotePolicy: "Onsite/Hybrid",
    careersPage: "https://www.apparelgroup.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Apparel Group's fashion/lifestyle e-commerce arm.",
  },
  {
    id: "floward",
    sheet: "MENA Ecommerce",
    company: "Floward",
    hqCountry: "UAE/Saudi",
    remotePolicy: "Onsite/Hybrid",
    careersPage: "https://www.floward.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Flowers/gifting e-commerce, regional tech team.",
  },
  {
    id: "careem-uber-group",
    sheet: "MENA Ecommerce",
    company: "Careem (Uber group)",
    hqCountry: "UAE",
    remotePolicy: "Hybrid",
    careersPage: "https://www.careem.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Super-app incl. commerce/delivery; part of Uber.",
  },
  {
    id: "property-finder",
    sheet: "MENA Ecommerce",
    company: "Property Finder",
    hqCountry: "UAE",
    remotePolicy: "Hybrid",
    careersPage: "https://www.propertyfinder.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Not classic e-commerce but strong regional tech/QA org.",
  },
  {
    id: "bayzat",
    sheet: "MENA Ecommerce",
    company: "Bayzat",
    hqCountry: "UAE",
    remotePolicy: "Hybrid",
    careersPage: "https://www.bayzat.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "HR/insurtech platform, regional tech hiring.",
  },
  {
    id: "fetchr",
    sheet: "MENA Ecommerce",
    company: "Fetchr",
    hqCountry: "UAE",
    remotePolicy: "Onsite",
    careersPage: "Check LinkedIn company page",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Logistics-tech supporting UAE e-commerce.",
  },
  {
    id: "kitopi",
    sheet: "MENA Ecommerce",
    company: "Kitopi",
    hqCountry: "UAE",
    remotePolicy: "Hybrid",
    careersPage: "https://www.kitopi.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Cloud-kitchen tech; adjacent to food e-commerce.",
  },
  {
    id: "trukker",
    sheet: "MENA Ecommerce",
    company: "Trukker",
    hqCountry: "UAE/Saudi",
    remotePolicy: "Hybrid",
    careersPage: "https://www.trukker.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Logistics-tech platform supporting regional e-commerce.",
  },
  {
    id: "namshi-tech-aeon-al-futtaim-digital",
    sheet: "MENA Ecommerce",
    company: "Namshi Tech / Aeon (Al-Futtaim digital)",
    hqCountry: "UAE",
    remotePolicy: "Hybrid",
    careersPage: "https://www.alfuttaim.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Al-Futtaim's digital/e-commerce tech arm.",
  },
  {
    id: "extra-saudi-electronics-e-com",
    sheet: "MENA Ecommerce",
    company: "Extra (Saudi electronics e-com)",
    hqCountry: "Saudi Arabia",
    remotePolicy: "Onsite",
    careersPage: "https://www.extra.com/en-sa/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Major Saudi electronics retailer with e-commerce arm.",
  },
  {
    id: "jahez",
    sheet: "MENA Ecommerce",
    company: "Jahez",
    hqCountry: "Saudi Arabia",
    remotePolicy: "Hybrid",
    careersPage: "https://www.jahez.net/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Saudi food delivery/quick-commerce, listed company.",
  },
  {
    id: "noon-food",
    sheet: "MENA Ecommerce",
    company: "Noon Food",
    hqCountry: "UAE",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.noon.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Noon's food-delivery vertical, shared careers portal.",
  },
  {
    id: "mumzworld",
    sheet: "MENA Ecommerce",
    company: "Mumzworld",
    hqCountry: "UAE",
    remotePolicy: "Onsite",
    careersPage: "https://www.mumzworld.com/en-ae/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "MENA-focused mother & baby e-commerce.",
  },
  {
    id: "amazon-global",
    sheet: "Global Ecommerce",
    company: "Amazon (global)",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (varies)",
    careersPage: "https://www.amazon.jobs",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Filter Location = Remote; large SDET/QA org.",
  },
  {
    id: "shopify",
    sheet: "Global Ecommerce",
    company: "Shopify",
    hqCountry: "Canada",
    remotePolicy: "Remote-first",
    careersPage: "https://www.shopify.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Digital by Default policy; hires QA globally.",
  },
  {
    id: "ebay",
    sheet: "Global Ecommerce",
    company: "eBay",
    hqCountry: "USA",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.ebayinc.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Some remote-eligible QA automation roles.",
  },
  {
    id: "etsy",
    sheet: "Global Ecommerce",
    company: "Etsy",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://careers.etsy.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Mostly US remote-eligible.",
  },
  {
    id: "wayfair",
    sheet: "Global Ecommerce",
    company: "Wayfair",
    hqCountry: "USA",
    remotePolicy: "Hybrid",
    careersPage: "https://www.aboutwayfair.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Large QA engineering org, US/EU offices.",
  },
  {
    id: "zalando",
    sheet: "Global Ecommerce",
    company: "Zalando",
    hqCountry: "Germany",
    remotePolicy: "Hybrid/Remote (EU)",
    careersPage: "https://jobs.zalando.com/en/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "EU remote flexibility for many tech roles.",
  },
  {
    id: "asos",
    sheet: "Global Ecommerce",
    company: "ASOS",
    hqCountry: "UK",
    remotePolicy: "Hybrid",
    careersPage: "https://www.asosplc.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Mostly UK-based eligibility.",
  },
  {
    id: "booking-com",
    sheet: "Global Ecommerce",
    company: "Booking.com",
    hqCountry: "Netherlands",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.booking.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Travel e-commerce; EU remote-eligible roles exist.",
  },
  {
    id: "alibaba-group",
    sheet: "Global Ecommerce",
    company: "Alibaba Group",
    hqCountry: "China",
    remotePolicy: "Onsite",
    careersPage: "https://careers.alibabagroup.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Mostly on-site China/regional hubs.",
  },
  {
    id: "jd-com",
    sheet: "Global Ecommerce",
    company: "JD.com",
    hqCountry: "China",
    remotePolicy: "Onsite",
    careersPage: "https://jd.jobs/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Mostly China-based hiring.",
  },
  {
    id: "shein",
    sheet: "Global Ecommerce",
    company: "Shein",
    hqCountry: "Singapore",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.shein.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Expanding int'l QA teams; some remote in EU/US hubs.",
  },
  {
    id: "temu-pdd-holdings",
    sheet: "Global Ecommerce",
    company: "Temu (PDD Holdings)",
    hqCountry: "China/USA",
    remotePolicy: "Hybrid",
    careersPage: "https://www.temu.com/join-us.html",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Rapidly scaling; check often.",
  },
  {
    id: "walmart-global-tech",
    sheet: "Global Ecommerce",
    company: "Walmart Global Tech",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://careers.walmart.com/global-tech",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Some remote-eligible US QA roles.",
  },
  {
    id: "chewy",
    sheet: "Global Ecommerce",
    company: "Chewy",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://careers.chewy.com/us/en",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Pet e-commerce; remote QA roles for US-based.",
  },
  {
    id: "instacart",
    sheet: "Global Ecommerce",
    company: "Instacart",
    hqCountry: "USA",
    remotePolicy: "Remote-friendly",
    careersPage: "https://instacart.careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Grocery delivery; remote engineering culture.",
  },
  {
    id: "rakuten",
    sheet: "Global Ecommerce",
    company: "Rakuten",
    hqCountry: "Japan",
    remotePolicy: "Hybrid",
    careersPage: "https://global.rakuten.com/corp/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Diversified e-commerce group, global offices.",
  },
  {
    id: "flipkart",
    sheet: "Global Ecommerce",
    company: "Flipkart",
    hqCountry: "India",
    remotePolicy: "Hybrid",
    careersPage: "https://www.flipkartcareers.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Mostly India-based, some remote-flexible.",
  },
  {
    id: "mercado-libre",
    sheet: "Global Ecommerce",
    company: "Mercado Libre",
    hqCountry: "Argentina",
    remotePolicy: "Hybrid/Remote (LatAm)",
    careersPage: "https://careers.mercadolibre.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Remote common within LatAm region.",
  },
  {
    id: "coupang",
    sheet: "Global Ecommerce",
    company: "Coupang",
    hqCountry: "South Korea",
    remotePolicy: "Onsite",
    careersPage: "https://www.coupang.jobs/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Mostly Korea-based.",
  },
  {
    id: "farfetch",
    sheet: "Global Ecommerce",
    company: "Farfetch",
    hqCountry: "UK/Portugal",
    remotePolicy: "Hybrid",
    careersPage: "https://www.farfetchcareers.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Luxury fashion e-commerce.",
  },
  {
    id: "zappos",
    sheet: "Global Ecommerce",
    company: "Zappos",
    hqCountry: "USA (Amazon subsidiary)",
    remotePolicy: "Onsite/Hybrid",
    careersPage: "https://www.zappos.com/jobs",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Also posted via Amazon.jobs.",
  },
  {
    id: "wish-contextlogic",
    sheet: "Global Ecommerce",
    company: "Wish (ContextLogic)",
    hqCountry: "USA",
    remotePolicy: "Remote-friendly",
    careersPage: "https://www.wish.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Smaller QA team; check periodically.",
  },
  {
    id: "delivery-hero",
    sheet: "Global Ecommerce",
    company: "Delivery Hero",
    hqCountry: "Germany",
    remotePolicy: "Hybrid/Remote (varies)",
    careersPage: "https://careers.deliveryhero.com/global/en",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Parent of Talabat/InstaShop; bridges your UAE background.",
  },
  {
    id: "otto-group",
    sheet: "Global Ecommerce",
    company: "Otto Group",
    hqCountry: "Germany",
    remotePolicy: "Hybrid",
    careersPage: "https://www.ottogroup.com/en/karriere/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "One of Europe's largest online retailers.",
  },
  {
    id: "cdiscount",
    sheet: "Global Ecommerce",
    company: "Cdiscount",
    hqCountry: "France",
    remotePolicy: "Hybrid",
    careersPage: "https://recrutement.cdiscount.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Major French e-commerce marketplace.",
  },
  {
    id: "allegro",
    sheet: "Global Ecommerce",
    company: "Allegro",
    hqCountry: "Poland",
    remotePolicy: "Hybrid/Remote (Poland)",
    careersPage: "https://allegro.pl/kariera",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Poland's largest online marketplace.",
  },
  {
    id: "mediamarktsaturn",
    sheet: "Global Ecommerce",
    company: "MediaMarktSaturn",
    hqCountry: "Germany",
    remotePolicy: "Hybrid",
    careersPage: "https://karriere.mediamarktsaturn.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Electronics retail + e-commerce.",
  },
  {
    id: "ceneo-grupa-eurocash",
    sheet: "Global Ecommerce",
    company: "Ceneo/Grupa Eurocash",
    hqCountry: "Poland",
    remotePolicy: "Hybrid",
    careersPage: "Check LinkedIn company page",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Regional e-commerce/price-comparison platform.",
  },
  {
    id: "takealot",
    sheet: "Global Ecommerce",
    company: "Takealot",
    hqCountry: "South Africa",
    remotePolicy: "Hybrid",
    careersPage: "https://www.takealot.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "South Africa's largest online retailer.",
  },
  {
    id: "jumia",
    sheet: "Global Ecommerce",
    company: "Jumia",
    hqCountry: "Nigeria/Pan-Africa",
    remotePolicy: "Hybrid/Remote (Africa)",
    careersPage: "https://group.jumia.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Pan-African e-commerce; distributed tech teams.",
  },
  {
    id: "trendyol",
    sheet: "Global Ecommerce",
    company: "Trendyol",
    hqCountry: "Turkey",
    remotePolicy: "Hybrid",
    careersPage: "https://www.trendyol.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Turkey's largest e-commerce platform.",
  },
  {
    id: "hepsiburada",
    sheet: "Global Ecommerce",
    company: "Hepsiburada",
    hqCountry: "Turkey",
    remotePolicy: "Hybrid",
    careersPage: "https://www.hepsiburada.com/kariyer",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Major Turkish e-commerce competitor to Trendyol.",
  },
  {
    id: "ozon",
    sheet: "Global Ecommerce",
    company: "OZON",
    hqCountry: "Russia",
    remotePolicy: "Hybrid",
    careersPage: "https://ozon.tech/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Russia's largest e-commerce/marketplace tech org.",
  },
  {
    id: "wildberries",
    sheet: "Global Ecommerce",
    company: "Wildberries",
    hqCountry: "Russia",
    remotePolicy: "Hybrid",
    careersPage: "Check LinkedIn company page",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Large Russian fashion/general e-commerce.",
  },
  {
    id: "lazada-alibaba-group",
    sheet: "Global Ecommerce",
    company: "Lazada (Alibaba group)",
    hqCountry: "Singapore",
    remotePolicy: "Hybrid",
    careersPage: "https://www.lazada.com/en/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Southeast Asia's leading marketplace.",
  },
  {
    id: "shopee-sea-ltd",
    sheet: "Global Ecommerce",
    company: "Shopee (Sea Ltd)",
    hqCountry: "Singapore",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.sea.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Southeast Asia/Taiwan/LatAm marketplace.",
  },
  {
    id: "tokopedia-goto-group",
    sheet: "Global Ecommerce",
    company: "Tokopedia (GoTo Group)",
    hqCountry: "Indonesia",
    remotePolicy: "Hybrid",
    careersPage: "https://www.gotocompany.com/en/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Indonesia's largest marketplace.",
  },
  {
    id: "rappi",
    sheet: "Global Ecommerce",
    company: "Rappi",
    hqCountry: "Colombia",
    remotePolicy: "Hybrid/Remote (LatAm)",
    careersPage: "https://about.rappi.com/en/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "LatAm quick-commerce super-app.",
  },
  {
    id: "meli-mercado-libre-logistics",
    sheet: "Global Ecommerce",
    company: "Meli (Mercado Libre logistics)",
    hqCountry: "Argentina",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.mercadolibre.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Same group as Mercado Libre.",
  },
  {
    id: "kaufland-e-commerce",
    sheet: "Global Ecommerce",
    company: "Kaufland e-commerce",
    hqCountry: "Germany",
    remotePolicy: "Hybrid",
    careersPage: "https://www.kaufland.com/company/jobs.html",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Schwarz Group's e-commerce arm.",
  },
  {
    id: "zalora",
    sheet: "Global Ecommerce",
    company: "Zalora",
    hqCountry: "Singapore",
    remotePolicy: "Hybrid",
    careersPage: "https://www.zalora.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Global Fashion Group's SE Asia fashion e-commerce.",
  },
  {
    id: "about-you",
    sheet: "Global Ecommerce",
    company: "About You",
    hqCountry: "Germany",
    remotePolicy: "Hybrid/Remote (EU)",
    careersPage: "https://jobs.aboutyou.de/en/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "German fashion e-commerce, tech-forward culture.",
  },
  {
    id: "thg-the-hut-group",
    sheet: "Global Ecommerce",
    company: "THG (The Hut Group)",
    hqCountry: "UK",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.thg.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "UK e-commerce group (Lookfantastic, Myprotein etc.).",
  },
  {
    id: "boohoo-group",
    sheet: "Global Ecommerce",
    company: "Boohoo Group",
    hqCountry: "UK",
    remotePolicy: "Hybrid",
    careersPage: "https://www.boohooplc.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Fast-fashion e-commerce group.",
  },
  {
    id: "next-plc",
    sheet: "Global Ecommerce",
    company: "Next plc",
    hqCountry: "UK",
    remotePolicy: "Hybrid",
    careersPage: "https://www.nextplc.co.uk/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "UK retail + strong e-commerce arm.",
  },
  {
    id: "otto-bonprix",
    sheet: "Global Ecommerce",
    company: "Otto/Bonprix",
    hqCountry: "Germany",
    remotePolicy: "Hybrid",
    careersPage: "https://jobs.bonprix.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Fashion e-commerce, part of Otto Group.",
  },
  {
    id: "vinted",
    sheet: "Global Ecommerce",
    company: "Vinted",
    hqCountry: "Lithuania",
    remotePolicy: "Remote-friendly (EU)",
    careersPage: "https://vinted.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "C2C fashion resale marketplace, EU remote culture.",
  },
  {
    id: "depop-etsy-group",
    sheet: "Global Ecommerce",
    company: "Depop (Etsy group)",
    hqCountry: "UK",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.etsy.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Resale fashion marketplace, part of Etsy.",
  },
  {
    id: "stockx",
    sheet: "Global Ecommerce",
    company: "StockX",
    hqCountry: "USA",
    remotePolicy: "Hybrid",
    careersPage: "https://stockx.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Sneaker/streetwear resale marketplace.",
  },
  {
    id: "poshmark",
    sheet: "Global Ecommerce",
    company: "Poshmark",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://careers.poshmark.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Social commerce/resale marketplace.",
  },
  {
    id: "thredup",
    sheet: "Global Ecommerce",
    company: "ThredUp",
    hqCountry: "USA",
    remotePolicy: "Remote-friendly (US)",
    careersPage: "https://www.thredup.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Online resale/thrift e-commerce.",
  },
  {
    id: "overstock-bed-bath-and-beyond-digital",
    sheet: "Global Ecommerce",
    company: "Overstock/Bed Bath & Beyond digital",
    hqCountry: "USA",
    remotePolicy: "Remote-friendly (US)",
    careersPage: "https://www.bbbyinc.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Digital-first US retailer.",
  },
  {
    id: "newegg",
    sheet: "Global Ecommerce",
    company: "Newegg",
    hqCountry: "USA",
    remotePolicy: "Hybrid",
    careersPage: "https://www.newegg.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Electronics-focused e-commerce marketplace.",
  },
  {
    id: "1688-alibaba-domestic-units",
    sheet: "Global Ecommerce",
    company: "1688/Alibaba domestic units",
    hqCountry: "China",
    remotePolicy: "Onsite",
    careersPage: "https://careers.alibabagroup.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Part of the wider Alibaba group.",
  },
  {
    id: "meituan",
    sheet: "Global Ecommerce",
    company: "Meituan",
    hqCountry: "China",
    remotePolicy: "Onsite",
    careersPage: "https://about.meituan.com/en/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Local commerce/delivery giant.",
  },
  {
    id: "makemytrip",
    sheet: "Global Ecommerce",
    company: "MakeMyTrip",
    hqCountry: "India",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.makemytrip.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Travel e-commerce; large QA org.",
  },
  {
    id: "myntra-flipkart-group",
    sheet: "Global Ecommerce",
    company: "Myntra (Flipkart group)",
    hqCountry: "India",
    remotePolicy: "Hybrid",
    careersPage: "https://careers.myntra.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Fashion e-commerce, part of Flipkart group.",
  },
  {
    id: "nykaa",
    sheet: "Global Ecommerce",
    company: "Nykaa",
    hqCountry: "India",
    remotePolicy: "Hybrid",
    careersPage: "https://www.nykaa.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Beauty & fashion e-commerce, listed company.",
  },
  {
    id: "snapdeal",
    sheet: "Global Ecommerce",
    company: "Snapdeal",
    hqCountry: "India",
    remotePolicy: "Hybrid",
    careersPage: "Check LinkedIn company page",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Indian value e-commerce marketplace.",
  },
  {
    id: "meesho",
    sheet: "Global Ecommerce",
    company: "Meesho",
    hqCountry: "India",
    remotePolicy: "Remote-friendly",
    careersPage: "https://careers.meesho.com/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "India's fast-growing social commerce platform.",
  },
  {
    id: "gitlab",
    sheet: "Remote-First Tech",
    company: "GitLab",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote (global)",
    careersPage: "https://about.gitlab.com/jobs/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "All-remote company, publishes hiring handbook; hires QA/SDET globally.",
  },
  {
    id: "automattic-wordpress-com",
    sheet: "Remote-First Tech",
    company: "Automattic (WordPress.com)",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote (global)",
    careersPage: "https://automattic.com/work-with-us/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Fully distributed; occasional QA/Test Engineer roles.",
  },
  {
    id: "zapier",
    sheet: "Remote-First Tech",
    company: "Zapier",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote (global)",
    careersPage: "https://zapier.com/jobs",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Fully remote, hires internationally as contractors/employees depending on country.",
  },
  {
    id: "doist-todoist",
    sheet: "Remote-First Tech",
    company: "Doist (Todoist)",
    hqCountry: "Portugal (fully remote)",
    remotePolicy: "Fully remote (global)",
    careersPage: "https://doist.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Small fully-remote team; occasional QA roles.",
  },
  {
    id: "buffer",
    sheet: "Remote-First Tech",
    company: "Buffer",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote (global)",
    careersPage: "https://buffer.com/journey",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Fully remote, transparent salary/hiring process.",
  },
  {
    id: "invision",
    sheet: "Remote-First Tech",
    company: "InVision",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote",
    careersPage: "https://www.invisionapp.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Design-tool company, historically fully remote.",
  },
  {
    id: "toptal",
    sheet: "Remote-First Tech",
    company: "Toptal",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote (global)",
    careersPage: "https://www.toptal.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Talent marketplace; hires internal QA plus freelance testers globally.",
  },
  {
    id: "basecamp-37signals",
    sheet: "Remote-First Tech",
    company: "Basecamp/37signals",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote",
    careersPage: "https://37signals.com/jobs",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Small remote team; infrequent postings.",
  },
  {
    id: "help-scout",
    sheet: "Remote-First Tech",
    company: "Help Scout",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote (US-leaning)",
    careersPage: "https://www.helpscout.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Customer-support SaaS, fully remote culture.",
  },
  {
    id: "postmark-activecampaign",
    sheet: "Remote-First Tech",
    company: "Postmark/ActiveCampaign",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote",
    careersPage: "https://www.activecampaign.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Marketing/e-commerce-adjacent SaaS.",
  },
  {
    id: "automattic-owned-woocommerce",
    sheet: "Remote-First Tech",
    company: "Automattic-owned WooCommerce",
    hqCountry: "USA (fully remote)",
    remotePolicy: "Fully remote (global)",
    careersPage: "https://automattic.com/work-with-us/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "WooCommerce e-commerce platform, same hiring portal as Automattic.",
  },
  {
    id: "bigcommerce",
    sheet: "Remote-First Tech",
    company: "BigCommerce",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://www.bigcommerce.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce platform (Shopify competitor); some remote QA roles.",
  },
  {
    id: "squarespace",
    sheet: "Remote-First Tech",
    company: "Squarespace",
    hqCountry: "USA",
    remotePolicy: "Hybrid",
    careersPage: "https://www.squarespace.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Website/e-commerce builder.",
  },
  {
    id: "wix",
    sheet: "Remote-First Tech",
    company: "Wix",
    hqCountry: "Israel",
    remotePolicy: "Hybrid",
    careersPage: "https://www.wix.com/jobs/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Website/e-commerce builder, large QA org.",
  },
  {
    id: "klaviyo",
    sheet: "Remote-First Tech",
    company: "Klaviyo",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://www.klaviyo.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce marketing platform, integrates with Shopify.",
  },
  {
    id: "recharge",
    sheet: "Remote-First Tech",
    company: "Recharge",
    hqCountry: "USA",
    remotePolicy: "Fully remote (US)",
    careersPage: "https://getrecharge.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Subscription e-commerce platform, remote-first.",
  },
  {
    id: "gorgias",
    sheet: "Remote-First Tech",
    company: "Gorgias",
    hqCountry: "USA/France",
    remotePolicy: "Remote-friendly",
    careersPage: "https://www.gorgias.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce customer-support platform.",
  },
  {
    id: "yotpo",
    sheet: "Remote-First Tech",
    company: "Yotpo",
    hqCountry: "Israel/USA",
    remotePolicy: "Hybrid",
    careersPage: "https://www.yotpo.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce marketing/reviews platform.",
  },
  {
    id: "bold-commerce",
    sheet: "Remote-First Tech",
    company: "Bold Commerce",
    hqCountry: "Canada",
    remotePolicy: "Fully remote (Canada-leaning)",
    careersPage: "https://boldcommerce.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce infrastructure/apps for Shopify.",
  },
  {
    id: "attentive",
    sheet: "Remote-First Tech",
    company: "Attentive",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://attentive.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce SMS marketing platform.",
  },
  {
    id: "global-e",
    sheet: "Remote-First Tech",
    company: "Global-E",
    hqCountry: "Israel",
    remotePolicy: "Hybrid",
    careersPage: "https://www.global-e.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Cross-border e-commerce enablement platform.",
  },
  {
    id: "shipbob",
    sheet: "Remote-First Tech",
    company: "ShipBob",
    hqCountry: "USA",
    remotePolicy: "Hybrid/Remote (US)",
    careersPage: "https://www.shipbob.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce fulfillment tech.",
  },
  {
    id: "deliverr-flexport",
    sheet: "Remote-First Tech",
    company: "Deliverr (Flexport)",
    hqCountry: "USA",
    remotePolicy: "Hybrid",
    careersPage: "https://www.flexport.com/careers/",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce logistics/fulfillment, part of Flexport.",
  },
  {
    id: "rebuy-engine",
    sheet: "Remote-First Tech",
    company: "Rebuy Engine",
    hqCountry: "USA",
    remotePolicy: "Fully remote",
    careersPage: "https://www.rebuyengine.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "Shopify personalization app, small remote team.",
  },
  {
    id: "loop-returns",
    sheet: "Remote-First Tech",
    company: "Loop Returns",
    hqCountry: "USA",
    remotePolicy: "Fully remote (US)",
    careersPage: "https://loopreturns.com/careers",
    hrEmail: "Not publicly available — apply via careers portal / LinkedIn",
    notes: "E-commerce returns platform, remote-first.",
  },
];
