import { Job } from "./types";

// Sourced primarily from Indeed's job search API on 2026-08-08.
// LinkedIn, Naukri, Bayt and several other boards block automated fetching,
// so this seed set leans on Indeed plus a couple of directly-fetchable ATS pages.
// Add more jobs here as you find them — keep applyUrl pointed at the real posting,
// and only fill hrEmail when a contact address is genuinely published in the listing.
export const jobs: Job[] = [
  // ---------- INDIA ----------
  {
    id: "infomaze-qa-engineer",
    title: "QA Engineer – Manual & Automation",
    company: "Infomaze",
    location: "Mysuru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-02-27",
    summary:
      "Ensure flawless software performance across platforms through comprehensive manual and automated testing before release.",
    highlights: [
      "Own manual and automated test coverage across web and platform releases",
      "Play a critical role in maintaining product quality gates before release",
    ],
    skills: ["Manual Testing", "Automation Testing"],
    applyUrl: "https://to.indeed.com/aarsbpgrfzry",
    source: "Indeed",
  },
  {
    id: "goguardian-senior-qa-lead",
    title: "Senior Quality Assurance Engineering Lead",
    company: "GoGuardian",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: true,
    seniority: "Lead",
    employmentType: "Internship",
    postedDate: "2026-07-29",
    summary:
      "Own QA strategy and execution for a product area at a K-12 ed-tech company, leading test planning, automation strategy, and mentoring across a remote engineering org.",
    highlights: [
      "Own QA strategy, test planning, and release-readiness for an assigned product area",
      "Lead manual, API, integration, and automation testing across web applications",
      "Hands-on with Playwright, Cypress, or Selenium; guide CI/CD failure investigation",
      "Mentor QA engineers and drive adoption of AI-assisted QA workflows",
    ],
    skills: ["Test Strategy", "Playwright", "Cypress", "Selenium", "CI/CD", "Mentoring"],
    applyUrl: "https://to.indeed.com/aatwtdztywbm",
    source: "Indeed",
  },
  {
    id: "infobeans-qa-engineer",
    title: "QA Engineer",
    company: "InfoBeans",
    location: "Viman Nagar, Pune, Maharashtra, India",
    region: "India",
    remote: false,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-08-03",
    summary: "QA role at InfoBeans, a Pune-based digital engineering services company.",
    highlights: ["Full-time QA position based out of InfoBeans' Viman Nagar, Pune office"],
    skills: ["Software Testing"],
    applyUrl: "https://to.indeed.com/aapfkzc7zt89",
    source: "Indeed",
  },
  {
    id: "clarivate-lead-qa-automation",
    title: "Lead Quality Assurance Engineer (Selenium, Playwright)",
    company: "Clarivate",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Lead",
    employmentType: "Full-time",
    postedDate: "2026-08-06",
    summary:
      "Lead QA Automation Engineer role owning enterprise-scale automation frameworks across UI, API, and data validation for Clarivate's Quality Engineering team.",
    highlights: [
      "7+ years QA/automation experience, 3+ years leading automation initiatives",
      "Design enterprise-scale automation frameworks from the ground up",
      "Hands-on with Selenium, Playwright, JavaScript, TypeScript, and Python",
      "Own end-to-end automation strategy including Salesforce, UI, API, and data validation",
      "40h/week, fulltime in IST timezone",
    ],
    skills: ["Selenium", "Playwright", "TypeScript", "Python", "CI/CD", "Data Validation"],
    applyUrl: "https://to.indeed.com/aadggp7fd48c",
    source: "Indeed",
  },
  {
    id: "synchrony-avp-qe-lead",
    title: "AVP, Quality Engineering Lead (L10)",
    company: "Synchrony",
    location: "Hyderabad, Telangana, India",
    region: "India",
    remote: false,
    seniority: "Manager",
    employmentType: "Full-time",
    postedDate: "2026-06-19",
    salary: undefined,
    summary:
      "Lead quality engineering for API/service-layer products on AWS cloud-native infrastructure at Synchrony, owning automation strategy across Lambda, EKS, and Step Functions.",
    highlights: [
      "5+ years in QA/Testing with 2+ years leading QA or owning quality for a team",
      "Own QE strategy for API releases: functional, integration, regression, contract testing",
      "Java + Cucumber (BDD) automation, Allure reporting, ALM/Octane test management",
      "Deep testing expertise across AWS Lambda, S3, EKS, Step Functions, AuroraDB",
      "Work timing 2 PM–11 PM IST, overlap window with US Eastern hours",
    ],
    skills: ["Java", "Cucumber", "AWS", "API Testing", "CI/CD", "Team Leadership"],
    applyUrl: "https://to.indeed.com/aavgswy4f897",
    source: "Indeed",
  },
  {
    id: "deloitte-manager-automation-qe",
    title: "Manager | Automation | Quality Engineering",
    company: "Deloitte",
    location: "Chennai, Tamil Nadu, India",
    region: "India",
    remote: false,
    seniority: "Manager",
    employmentType: "Full-time",
    postedDate: "2026-08-06",
    summary:
      "Playwright automation engineering manager role within Deloitte's Technology & Transformation practice, owning automated test scripts for web applications.",
    highlights: [
      "10–13 years of experience required",
      "Automation testing in Java, Playwright, BDD-Cucumber, API testing (Postman/REST Assured)",
      "Design, develop, and maintain automated test scripts for web applications",
      "Backend/database testing plus CI/CD enablement on cloud infrastructure",
    ],
    skills: ["Java", "Playwright", "Cucumber", "Postman", "REST Assured", "CI/CD"],
    applyUrl: "https://to.indeed.com/aa44r4qcqd6s",
    source: "Indeed",
  },
  {
    id: "epic-kids-qa-engineer",
    title: "QA Engineer (India, Remote)",
    company: "Epic! (Epic Kids)",
    location: "Bengaluru, Karnataka, India · Remote",
    region: "India",
    remote: true,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-07-16",
    summary:
      "Remote India-based QA Engineer for Epic's digital reading platform, owning quality across web, iOS, and Android apps with daily US-hours overlap.",
    highlights: [
      "3+ years hands-on manual test planning and execution",
      "Test native mobile apps on real iOS and Android devices, cross-browser web testing",
      "Own release verification: smoke/sanity passes and QA sign-off before ship",
      "Build automated UI/end-to-end and API tests with Playwright or Cypress",
      "Remote, India-based; requires daily overlap with US working hours",
    ],
    skills: ["Manual Testing", "Mobile QA", "Playwright", "Cypress", "Jira", "API Testing"],
    applyUrl: "https://to.indeed.com/aaqfnyjrqphp",
    source: "Indeed",
  },
  {
    id: "zyxware-senior-test-engineer",
    title: "Senior Software Test Engineer",
    company: "Zyxware Technologies",
    location: "Kochi, Kerala, India",
    region: "India",
    remote: false,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-02-27",
    summary:
      "Lead a team of testers at Zyxware, owning test strategy, NFR testing (SEO/security/accessibility/performance), and client-facing QA delivery.",
    highlights: [
      "2+ years leading a testing team; B.Tech/MCA required",
      "Develop test plans and testing strategy end-to-end",
      "Cross-browser, responsive, and mobile app testing",
      "Automation framework experience with Behat/Cypress is a plus",
      "Hybrid: work from home with in-office days as needed (Kochi/Bangalore/Trivandrum)",
    ],
    skills: ["Test Strategy", "Cypress", "Cross-browser Testing", "Team Leadership"],
    applyUrl: "https://to.indeed.com/aab4y9pdbtvc",
    source: "Indeed",
  },
  {
    id: "genpact-lead-testing-qa",
    title: "Lead – Testing & Quality Assurance",
    company: "Genpact",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Lead",
    employmentType: "Full-time",
    postedDate: "2026-08-04",
    summary:
      "Lead testing strategy and execution for Genpact's AI Gigafactory engineering programs, managing a team of testers and driving defect analysis.",
    highlights: [
      "Develop and implement testing strategies for software applications",
      "Lead a team of testers to execute test plans and identify defects",
      "Collaborate with development teams on test coverage and quality standards",
      "Skills: API Testing, Postman, Regression Testing, UAT, SOA/Web Service Testing",
      "Hybrid work model",
    ],
    skills: ["API Testing", "Postman", "Regression Testing", "UAT", "Team Leadership"],
    applyUrl: "https://to.indeed.com/aam9xyxdlmnm",
    source: "Indeed",
  },
  {
    id: "particle41-qa-engineer",
    title: "Quality Assurance Engineer (IC2)",
    company: "Particle41",
    location: "Pune, Maharashtra, India",
    region: "India",
    remote: false,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-06-17",
    summary:
      "Own customer-experience-focused QA from early design through production release, blending automation with AI-augmented testing practices.",
    highlights: [
      "3–8 years of software quality engineering experience",
      "Write automated suites across UI, API, contract, and integration layers with TypeScript and Puppeteer",
      "Run OWASP Top 10 security checks and manual accessibility validation",
      "Maintain CI/CD quality gates and own post-deploy validation",
      "ISTQB Advanced certification strongly recommended",
    ],
    skills: ["TypeScript", "Puppeteer", "API Testing", "OWASP", "Accessibility Testing", "CI/CD"],
    applyUrl: "https://to.indeed.com/aazvrd8q7pft",
    source: "Indeed",
  },
  {
    id: "indium-test-engineer",
    title: "Test Engineer (Game QA)",
    company: "Indium Software",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Engineer",
    employmentType: "Permanent",
    postedDate: "2026-06-17",
    summary:
      "Junior tester role focused on mobile game, voice app, and community app testing across Android device variants.",
    highlights: [
      "1–2 years of experience testing mobile games, voice apps, or community apps",
      "Execute test cases written by Lead/Senior; cover Android device/OEM edge cases",
      "Run regression testing on stable flows every sprint cycle",
      "Report bugs clearly with reproduction steps, device details, and build version",
    ],
    skills: ["Game Testing", "Regression Testing", "Mobile QA", "Bug Reporting"],
    applyUrl: "https://to.indeed.com/aadwpmthrftm",
    source: "Indeed",
  },
  {
    id: "massive-mobility-qa-test-engineer",
    title: "QA/Test Engineer",
    company: "Massive Mobility",
    location: "Noida, Uttar Pradesh, India",
    region: "India",
    remote: false,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-03-31",
    summary:
      "Test Android, iOS, and Web platforms for an EV-charging infrastructure startup, owning quality across the full product lifecycle.",
    highlights: [
      "2+ years of manual QA/testing experience across Android, iOS, and Web",
      "Design QA strategies, organize phased testing, investigate errors, support fixes",
      "In-office, Noida",
    ],
    skills: ["Manual Testing", "Mobile QA", "Web Testing"],
    applyUrl: "https://to.indeed.com/aakk9fxhh9q8",
    source: "Indeed",
  },
  {
    id: "mybeacon-qa-engineer-remote",
    title: "QA Engineer (India – Remote)",
    company: "My Beacon",
    location: "Mumbai, Maharashtra, India · Remote",
    region: "India",
    remote: true,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-03-20",
    summary:
      "Remote QA role for a Canadian immigration fintech's customer-facing web and mobile apps, combining manual testing with scalable automation.",
    highlights: [
      "5+ years of experience, mix of manual and automated testing",
      "Hands-on with Selenium (or similar) and RESTful API testing",
      "Cross-browser/cross-device testing with BrowserStack",
      "Integrate automated tests into CI/CD; nice-to-have: Appium, AWS, Docker",
    ],
    skills: ["Selenium", "API Testing", "BrowserStack", "CI/CD", "Appium"],
    applyUrl: "https://to.indeed.com/aavnc6gvcf2z",
    source: "Indeed",
  },
  {
    id: "reizend-senior-test-automation",
    title: "Senior Test Automation Engineer (AI-First QA)",
    company: "Reizend Private Limited",
    location: "Remote, India",
    region: "India",
    remote: true,
    seniority: "Senior",
    employmentType: "Permanent",
    postedDate: "2026-07-30",
    salary: "₹12,00,000 – ₹24,00,000 / year",
    summary:
      "Lead adoption of AI-powered testing methodologies — self-healing automation, AI-assisted test generation — while building conventional automation frameworks across web, mobile, and API.",
    highlights: [
      "3–6 years hands-on automation and quality engineering experience",
      "Strong with Playwright, Selenium, Cypress, or Appium; CI/CD integration",
      "Define AI-first testing strategy, governance standards, and adoption roadmaps",
      "Working hours 6:30 PM–2:30 AM IST; fully remote",
    ],
    skills: ["Playwright", "Selenium", "Cypress", "Appium", "AI-assisted Testing", "CI/CD"],
    applyUrl: "https://to.indeed.com/aavrk7c8wvlm",
    source: "Indeed",
  },
  {
    id: "novature-senior-manual-qa",
    title: "Senior Manual QA Engineer",
    company: "Novature Tech",
    location: "Chennai, Tamil Nadu, India · Remote",
    region: "India",
    remote: true,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-02-26",
    summary:
      "Senior manual QA role spanning Web/UI/API/SAP testing with a strong SQL and Agile background; remote work offered.",
    highlights: [
      "8–12 years of professional QA testing experience",
      "3+ years with Jira for project management; solid SQL/No-SQL understanding",
      "Thorough understanding of Web/UI/API/SAP testing",
      "Remote work offered",
    ],
    skills: ["Manual Testing", "SQL", "Jira", "API Testing", "SAP Testing"],
    applyUrl: "https://to.indeed.com/aagkg6xkzqgk",
    source: "Indeed",
  },
  {
    id: "netsmart-manager-qa-engineering",
    title: "Manager, QA Engineering",
    company: "Netsmart Technologies",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Manager",
    employmentType: "Full-time",
    postedDate: "2026-06-16",
    summary:
      "Senior QA leadership role at a US healthcare HIT company, setting QA strategy across departments and building a scalable, compliance-aware quality culture.",
    highlights: [
      "14+ years of QA, software engineering, or test automation experience",
      "Track record building and scaling QA functions in healthcare organizations",
      "Establish scalable test automation and performance testing systems",
      "Hire, mentor, and develop senior QA talent across multiple sites",
      "Confidence working with C-suite, product, and engineering leadership",
    ],
    skills: ["QA Strategy", "Test Automation", "People Management", "Compliance"],
    applyUrl: "https://to.indeed.com/aamltjw8fkfc",
    source: "Indeed",
  },
  {
    id: "socgen-lead-qa-servicenow",
    title: "Lead Quality Assurance Engineer – ServiceNow",
    company: "Société Générale",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Lead",
    employmentType: "Permanent",
    postedDate: "2026-07-09",
    summary:
      "QA Lead validating ServiceNow platform customizations and their interactions with Société Générale's core information systems.",
    highlights: [
      "Define test strategy with the project team; validate ServiceNow configurations",
      "Develop and execute test plans, test cases, and scripts for functional/regression testing",
      "Automate test case execution as early as possible in the development lifecycle",
      "Identify, document, and track defects across ServiceNow and SG application teams",
    ],
    skills: ["ServiceNow", "Test Automation", "Regression Testing", "Defect Management"],
    applyUrl: "https://to.indeed.com/aa6tftw467gm",
    source: "Indeed",
  },
  {
    id: "netapp-director-sw-qa",
    title: "Director, SW QA Engineering",
    company: "NetApp",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Director",
    employmentType: "Full-time",
    postedDate: "2026-07-22",
    summary:
      "Lead NetApp's global Quality Assurance Center of Excellence, defining strategy and operating model for quality engineering across the enterprise application ecosystem.",
    highlights: [
      "Own strategy, operating model, and roadmap for a globally distributed QA organization",
      "Drive transformation toward an AI-first Quality Engineering model",
      "Own end-to-end business process validation across Commerce, ERP, Supply Chain, Service Management",
      "Establish quality governance frameworks, KPIs, and reporting mechanisms",
      "Bachelor's required, Master's preferred; hybrid work model",
    ],
    skills: ["QA Strategy", "AI Testing", "Governance", "Enterprise Systems", "Leadership"],
    applyUrl: "https://to.indeed.com/aazknrnn7hgd",
    source: "Indeed",
  },
  {
    id: "lg-ad-solutions-director-qa",
    title: "Director, Quality Assurance",
    company: "LG Ad Solutions",
    location: "Bengaluru, Karnataka, India",
    region: "India",
    remote: false,
    seniority: "Director",
    employmentType: "Full-time",
    postedDate: "2026-07-29",
    summary:
      "Lead and scale QA engineering strategy across products, platforms, and global delivery teams for a connected-TV advertising company.",
    highlights: [
      "12+ years of QA/Quality Engineering experience, 7+ years in senior leadership",
      "Define the org-wide QA and Quality Engineering strategy aligned to business goals",
      "Drive large-scale test automation modernization and shift-left testing",
      "Lead AI-enabled Quality Engineering strategy: AI-assisted test generation, predictive defect analysis",
      "Strong hands-on background with Playwright, Selenium, Cypress, or TestNG",
    ],
    skills: ["QA Leadership", "Test Automation", "AI Testing", "CI/CD", "Team Building"],
    applyUrl: "https://to.indeed.com/aatb8vpktzs7",
    source: "Indeed",
  },
  {
    id: "ttec-qa-sdet-lead",
    title: "QA / SDET Lead",
    company: "TTEC Digital",
    location: "Hyderabad, Telangana, India · Remote",
    region: "India",
    remote: true,
    seniority: "Lead",
    employmentType: "Full-time",
    postedDate: "2026-07-17",
    summary:
      "Player-coach QA/SDET Lead building automation-first quality engineering for an AI CX platform (voice, desktop, intelligence). Fully remote.",
    highlights: [
      "8+ years QA/SDET experience; automation-first, no manual QA on this team",
      "Own quality strategy across a 1-week sprint cadence and the cross-service contract suite",
      "Fast-turnaround regression suites, load/stress coverage, chaos/failure-injection testing",
      "Test event-driven systems, WebSocket flows, and evaluate non-deterministic LLM/ML outputs",
      "Fully remote role",
    ],
    skills: ["Test Automation", "SDET", "CI/CD", "Load Testing", "LLM Evaluation"],
    applyUrl: "https://to.indeed.com/aabfmbwj7nvh",
    source: "Indeed",
  },
  {
    id: "geakminds-qa-automation-lead",
    title: "QA Automation Lead / Senior QA Automation Engineer",
    company: "Geakminds",
    location: "Chennai, Tamil Nadu, India · Remote",
    region: "India",
    remote: true,
    seniority: "Lead",
    employmentType: "Full-time",
    postedDate: "2026-07-31",
    summary:
      "Build scalable automation frameworks and mentor QA engineers for global clients, with remote flexibility.",
    highlights: [
      "7+ years of experience",
      "Strong Playwright, TypeScript/JavaScript, and Python automation",
      "API and UI automation testing integrated with Jenkins/GitHub Actions/GitLab CI",
      "Mentor QA engineers and drive automation best practices",
      "Remote flexibility",
    ],
    skills: ["Playwright", "TypeScript", "Python", "API Testing", "CI/CD", "Mentoring"],
    applyUrl: "https://to.indeed.com/aamrpmg8nwbf",
    source: "Indeed",
  },
  {
    id: "ruminate-qa-tester-fresher",
    title: "Software Tester (Fresher – 6 Months Experience)",
    company: "Ruminate IT Solution",
    location: "Remote, India (Work from Home)",
    region: "India",
    remote: true,
    seniority: "Engineer",
    employmentType: "Full-time, Permanent",
    postedDate: "2026-07-27",
    summary:
      "Entry-level manual QA role for freshers, writing test cases and identifying defects with mentorship from experienced testers.",
    highlights: [
      "0–6 months of experience in software testing",
      "Write and execute test cases and scenarios; regression, functional, UI/UX testing",
      "Basic knowledge of bug tracking tools like Jira, Trello, or Bugzilla is a plus",
      "Work-from-home; day shift",
    ],
    skills: ["Manual Testing", "Bug Tracking", "Functional Testing"],
    applyUrl: "https://to.indeed.com/aads9zs2lh62",
    source: "Indeed",
  },

  // ---------- UAE ----------
  {
    id: "mccoin-senior-qa-fintech",
    title: "Senior Software Quality Assurance Engineer – FinTech / Virtual Assets",
    company: "McCoin Virtual Assets L.L.C.",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-07-27",
    salary: "From AED 8,000/month",
    summary:
      "Ensure quality, reliability, and production readiness of a virtual asset trading platform — KYC, trading, deposits, withdrawals, and blockchain-analysis integrations.",
    highlights: [
      "5+ years of software QA experience",
      "Strong API, web-platform, database, and automation-testing background",
      "Fintech, banking, payments, brokerage, crypto, or regulated financial services experience mandatory",
      "Familiarity with KYC/AML, trading, or wallet workflows is an advantage",
    ],
    skills: ["API Testing", "Automation Testing", "FinTech", "CI/CD", "SQL"],
    applyUrl: "https://to.indeed.com/aapvf46s8mrp",
    source: "Indeed",
  },
  {
    id: "deeplight-qa-engineer-data",
    title: "QA Engineer (Data Platform)",
    company: "DeepLight AI",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Engineer",
    employmentType: "Contract",
    postedDate: "2026-07-08",
    summary:
      "Own end-to-end verification of a financial-services data platform — pipelines, API layers, and Lakehouse (Bronze/Silver/Gold) data quality.",
    highlights: [
      "2–4 years QA/test automation experience on data-intensive or backend platforms",
      "Strong SQL and Python for test automation and data validation",
      "Hands-on with AWS (S3, Glue, Athena) and Medallion architecture",
      "Includes visa sponsorship and health insurance",
    ],
    skills: ["SQL", "Python", "AWS", "API Testing", "Data Validation"],
    applyUrl: "https://to.indeed.com/aafqgq2p2pnz",
    source: "Indeed",
  },
  {
    id: "blackstone-senior-qa-engineer",
    title: "Senior QA Engineer",
    company: "BlackStone eIT",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-08-05",
    summary:
      "Own quality for enterprise digital solutions across manual and automated testing, mentoring junior QA and reporting release readiness to stakeholders.",
    highlights: [
      "5+ years of QA experience, hands-on manual and automation testing",
      "Strong Java automation: Selenium WebDriver, REST Assured, TestNG/JUnit",
      "CI/CD with Azure DevOps or Jenkins; Git version control",
      "ISTQB certification and Dynamics 365/Power Platform experience preferred",
    ],
    skills: ["Java", "Selenium", "REST Assured", "TestNG", "CI/CD"],
    applyUrl: "https://to.indeed.com/aav4jyvht8bl",
    source: "Indeed",
  },
  {
    id: "lndmrk-senior-qa-engineer",
    title: "Senior QA Engineer (Build QA From Scratch)",
    company: "LNDMRK",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-05-13",
    summary:
      "Solo QA hire at an early-stage property marketplace, owning React/FastAPI test automation and building QA process from the ground up.",
    highlights: [
      "7+ years QA experience with an automation-first mindset",
      "Build automated test frameworks from scratch: Playwright/Cypress + Pytest",
      "Own coverage across listings, search, offers, payments (Stripe), and auth",
      "Equity participation; direct collaboration with founder and CTO",
    ],
    skills: ["Playwright", "Cypress", "Pytest", "FastAPI", "React", "Stripe Testing"],
    applyUrl: "https://to.indeed.com/aa4v9hz2dcy2",
    source: "Indeed",
  },
  {
    id: "sbs-quality-engineer-ii",
    title: "Quality Engineer II",
    company: "SBS",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Engineer",
    employmentType: "Permanent",
    postedDate: "2026-07-29",
    summary:
      "Quality engineering role on a Digital Banking Platform, contributing test strategy, automation, and risk-based testing throughout the SDLC.",
    highlights: [
      "3–6 years in Software QA or Quality Engineering",
      "Automated testing with Java, JavaScript, or TypeScript",
      "Tech stack includes Playwright, Appium, Selenium, REST Assured, BrowserStack",
      "Banking/financial services experience advantageous",
    ],
    skills: ["Java", "Playwright", "Appium", "Selenium", "REST Assured"],
    applyUrl: "https://to.indeed.com/aawvzqptq68f",
    source: "Indeed",
  },
  {
    id: "dailypoint-software-tester",
    title: "Software Tester (m/f/d)",
    company: "dailypoint™ (Toedt, Dr. Selk & Coll. GmbH)",
    location: "Dubai, UAE (Hybrid)",
    region: "UAE",
    remote: false,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-07-14",
    salary: "Up to AED 10,000/month",
    summary:
      "Ensure quality of sprint releases for a hotel-industry CRM platform, writing test automation scripts and collaborating directly with the Product Manager.",
    highlights: [
      "5 years test automation and API testing (Postman/Swagger) required",
      "2 years Jira and TypeScript experience required",
      "Develop integration, system, and automation test scenarios",
      "Hybrid remote in Dubai; flat-hierarchy, results-focused culture",
    ],
    skills: ["Test Automation", "Postman", "TypeScript", "Jira"],
    applyUrl: "https://to.indeed.com/aa9888lnh44t",
    hrEmail: "bewerbungen@dailypoint.net",
    source: "Indeed",
  },
  {
    id: "emirates-lead-qa-engineer",
    title: "Lead Quality Assurance Engineer",
    company: "The Emirates Group",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Lead",
    employmentType: "Full-time",
    postedDate: "2026-05-21",
    summary:
      "Lead QA Engineering for Network Operations day-of-operations systems at Emirates, where quality failures are felt directly by live airline operations.",
    highlights: [
      "5+ years IT experience in quality engineering roles; iSQI Certified Agile Tester",
      "3+ years with Selenium components, Protractor, Cucumber, Gherkin, JUnit, or TestNG",
      "Build automation frameworks from scratch for UI and API testing, integrated with CI/CD",
      "Airline operations, crew management, or other real-time high-dependency domain experience preferred",
    ],
    skills: ["Selenium", "Cucumber", "TestNG", "CI/CD", "Automation Frameworks"],
    applyUrl: "https://to.indeed.com/aatg9gpfnp7k",
    source: "Indeed",
  },
  {
    id: "gac-senior-qa-automation-tester",
    title: "Senior Quality Assurance Automation Tester",
    company: "GAC",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-06-10",
    summary:
      "Ensure quality of GAC Group IT's software applications across System, Integration, Sanity, and Regression testing.",
    highlights: [
      "Minimum 5 years STLC experience, 2+ years test automation",
      "Selenium with Java/.NET, TestNG, Maven, Git",
      "CI/CD hands-on with Jenkins/Azure DevOps; API testing via SoapUI/Postman/REST Assured",
      "ISTQB or agile certification preferred",
    ],
    skills: ["Selenium", "TestNG", "Maven", "Jenkins", "API Testing"],
    applyUrl: "https://to.indeed.com/aapr6td8d7fx",
    source: "Indeed",
  },
  {
    id: "qualitykiosk-test-manager",
    title: "Test Manager – Core Banking (Finacle 11.x)",
    company: "QualityKiosk",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Manager",
    employmentType: "Contract",
    postedDate: "2026-05-21",
    summary:
      "Lead end-to-end QA strategy for a large-scale Core Retail Banking transformation, covering Finacle 11.x rollout, SWIFT payments, and GCC regulatory compliance.",
    highlights: [
      "12+ years experience, minimum 5 years in QA management",
      "Own Master Test Plan and Test Strategy across SIT, UAT, Regression, Performance",
      "SME for International Funds Transfer: SWIFT ISO 20022 messaging, FCY clearing",
      "Manage a team of onshore/offshore functional testers; SteerCo-level reporting",
    ],
    skills: ["Test Management", "Core Banking", "SWIFT", "Finacle", "Stakeholder Management"],
    applyUrl: "https://to.indeed.com/aayjkftdgw26",
    source: "Indeed",
  },
  {
    id: "dicetek-software-quality-tester",
    title: "Software Quality Tester – HPS/WAY4",
    company: "DICETEK LLC",
    location: "Sharjah, UAE",
    region: "UAE",
    remote: false,
    seniority: "Engineer",
    employmentType: "Contract",
    postedDate: "2026-05-05",
    summary:
      "Test core banking and card systems (HPS, WAY4) for a banking-industry systems integrator in Sharjah.",
    highlights: [
      "3–5 years software testing/QA experience in banking",
      "Hands-on with Core Banking applications and card systems (HPS, WAY4)",
      "SQL, API testing, and basic scripting",
      "ISTQB Foundation or CSTE certification preferred",
    ],
    skills: ["Core Banking", "SQL", "API Testing", "Test Planning"],
    applyUrl: "https://to.indeed.com/aakkrgc4ftq8",
    source: "Indeed",
  },
  {
    id: "impronics-qa-automation-swift",
    title: "QA Automation Tester – Trade Finance Payments/SWIFT",
    company: "Impronics Technologies",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2025-07-24",
    summary:
      "Automation testing for Eximbills trade finance software, focused on SWIFT MT messages and ISO 20022 payment messaging flows.",
    highlights: [
      "3+ years of automation testing experience",
      "Strong hands-on Selenium, Cucumber, and Jenkins CI/CD",
      "SWIFT MT message formats and ISO 20022 payment messaging essential",
      "API testing with Postman/SoapUI plus SQL-based data validation",
    ],
    skills: ["Selenium", "Cucumber", "Jenkins", "SWIFT", "API Testing"],
    applyUrl: "https://to.indeed.com/aaqh2hs98szy",
    source: "Indeed",
  },
  {
    id: "dyson-senior-software-test-manager",
    title: "Senior Software Test Manager",
    company: "Dyson",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Manager",
    employmentType: "Full-time",
    postedDate: "2026-04-08",
    summary:
      "Own the quality and verification strategy across Dyson's embedded software, app, IoT, and cloud platforms, building and developing high-performing Test & QA teams.",
    highlights: [
      "15+ years in software/embedded/IoT/app/cloud testing, 7+ years managing Test & QA teams",
      "Technical direction for system, integration, protocol, connectivity, and security testing",
      "Drive innovation in HIL automation, simulation, and AI-enabled test methods",
      "Automation background in Python/C/Kotlin/Swift; BLE/Wi-Fi/MQTT protocol testing",
    ],
    skills: ["Embedded Testing", "IoT", "Python", "Test Automation", "Team Leadership"],
    applyUrl: "https://to.indeed.com/aapbnycjqynt",
    source: "Indeed",
  },
  {
    id: "interel-senior-qa-manager",
    title: "Senior QA Manager (Embedded/IoT)",
    company: "Interel",
    location: "Dubai, UAE",
    region: "UAE",
    remote: false,
    seniority: "Manager",
    employmentType: "Full-time",
    postedDate: "2026-03-05",
    summary:
      "Own end-to-end quality of embedded and IoT hospitality-tech solutions, building and leading a growing Embedded QA team and reporting directly to the CTO.",
    highlights: [
      "7+ years in QA/Testing, 2+ years in a management or team-lead capacity",
      "Proven embedded systems testing experience with a strong automation focus",
      "Experience with embedded communication protocols and cloud-connected products",
      "Startup mindset; basic coding skills in Python or JavaScript; ISTQB a plus",
    ],
    skills: ["Embedded Testing", "IoT", "Test Automation", "Python", "Team Leadership"],
    applyUrl: "https://to.indeed.com/aan967z8wxqv",
    source: "Indeed",
  },

  // ---------- REMOTE (Global) ----------
  {
    id: "intone-qa-test-automation-remote",
    title: "QA Test Automation Engineer",
    company: "Intone Networks",
    location: "Remote",
    region: "Remote",
    remote: true,
    seniority: "Engineer",
    employmentType: "Contract",
    postedDate: "2026-06-01",
    summary:
      "Enterprise-environment QA/automation contract role, supporting both automated and manual testing efforts in an Agile setting.",
    highlights: [
      "6+ years of software testing and QA experience within enterprise environments",
      "6+ years developing and executing automated test scripts using Selenium or comparable tools",
      "Strong communication and collaboration skills",
    ],
    skills: ["Selenium", "Automation Testing", "Agile"],
    applyUrl: "https://to.indeed.com/aak9gn9fz9px",
    source: "Indeed",
  },
  {
    id: "vgmt-automation-sdet-remote",
    title: "Automation SDET Test Engineer",
    company: "VGMT Global IT Solutions",
    location: "Remote",
    region: "Remote",
    remote: true,
    seniority: "Engineer",
    employmentType: "Contract",
    postedDate: "2026-08-03",
    salary: "$95,199 – $174,648 / year",
    summary:
      "Design and maintain automated test solutions across web and mobile (Android/iOS), integrating tests into CI/CD and running performance testing with LoadRunner.",
    highlights: [
      "Automated scripts using Selenium, TestNG, JUnit, Cucumber",
      "Mobile testing frameworks; Appium experience highly desirable",
      "API testing (Postman/REST Assured), SQL data validation",
      "CI/CD integration via Jenkins, GitLab, or Azure DevOps",
    ],
    skills: ["Selenium", "Appium", "TestNG", "API Testing", "CI/CD", "Performance Testing"],
    applyUrl: "https://to.indeed.com/aafqgsg6sq9k",
    source: "Indeed",
  },
  {
    id: "cabtek-servicenow-qa-remote",
    title: "ServiceNow QA Test Engineer",
    company: "Cab Tek",
    location: "Remote",
    region: "Remote",
    remote: true,
    seniority: "Senior",
    employmentType: "Contract (12+ months)",
    postedDate: "2026-08-02",
    salary: "$52 – $55 / hour",
    summary:
      "Test ServiceNow version upgrades and custom applications across ITSM, ITOM, and ITAM modules for a long-term remote contract.",
    highlights: [
      "5+ years ServiceNow QA/testing experience, including version-upgrade regression",
      "Must have hands-on Selenium and Playwright experience",
      "Validate workflows, business rules, client scripts, UI policies, and integrations",
      "Experience with Jira, Azure DevOps, or ServiceNow Test Management",
    ],
    skills: ["ServiceNow", "Selenium", "Playwright", "Regression Testing"],
    applyUrl: "https://to.indeed.com/aasm2h47qjbn",
    source: "Indeed",
  },
  {
    id: "dexcom-sw-test-dev-engineer",
    title: "SW Test Development Engineer I",
    company: "Dexcom",
    location: "Remote",
    region: "Remote",
    remote: true,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-08-07",
    salary: "$71,600 – $119,300 / year",
    summary:
      "Build quality into backend services for a continuous glucose monitoring (CGM) data platform, designing automated tests for APIs and distributed cloud systems.",
    highlights: [
      "0–2 years related experience; Bachelor's in a technical discipline",
      "Automated tests for RESTful APIs, microservices, and backend components",
      "Experience with GCP, AWS, or Azure; Docker/Kubernetes a plus",
      "Familiarity with pytest, Robot Framework, or JUnit",
    ],
    skills: ["Python", "API Testing", "AWS", "Docker", "Microservices"],
    applyUrl: "https://to.indeed.com/aa9gp9ssplfv",
    source: "Indeed",
  },
  {
    id: "empower-staff-qa-automation",
    title: "Staff QA Automation Engineer",
    company: "Empower Pharmacy",
    location: "Remote",
    region: "Remote",
    remote: true,
    seniority: "Lead",
    employmentType: "Full-time",
    postedDate: "2026-08-07",
    summary:
      "Enterprise technical authority for quality engineering, owning automation architecture, governance, and AI-assisted testing strategy across a regulated healthcare environment.",
    highlights: [
      "12+ years of progressive QA/automation architecture experience",
      "Expert in Playwright, TypeScript, JavaScript, Node.js, and scalable framework design",
      "Own enterprise automation roadmap: UI, API, performance, accessibility, visual, E2E testing",
      "Lead root-cause investigation of the org's most complex automation/pipeline failures",
    ],
    skills: ["Playwright", "TypeScript", "Node.js", "CI/CD", "Performance Testing", "Leadership"],
    applyUrl: "https://to.indeed.com/aahctbswncdg",
    source: "Indeed",
  },
  {
    id: "quantumloopai-qa-india-remote",
    title: "Quality Assurance Engineer – India Remote",
    company: "QuantumLoopAI",
    location: "India · Remote (Work from Home)",
    region: "India",
    remote: true,
    seniority: "Senior",
    employmentType: "Full-time",
    postedDate: "2026-08-01",
    summary:
      "Build automated test coverage for a voice-AI platform serving NHS primary care — validating speech-to-text accuracy, text-to-speech quality, and call-flow correctness.",
    highlights: [
      "4+ years hands-on QA automation experience; strong daily Python scripting",
      "Automated test suites across API and UI layers; REST API and JSON testing",
      "Build outbound-call automation to validate the voice pipeline end-to-end",
      "Availability aligned to UK business hours (9 AM–6 PM GMT/BST)",
    ],
    skills: ["Python", "API Testing", "CI/CD", "Git", "Voice AI Testing"],
    applyUrl:
      "https://himalayas.app/companies/quantumloopai/jobs/quality-assurance-engineer-india-remote",
    source: "Himalayas",
  },
  {
    id: "drivetrain-qae-intern",
    title: "Quality Assurance Engineering (QAE) Intern",
    company: "Drivetrain",
    location: "India · Remote (Work from Home)",
    region: "India",
    remote: true,
    seniority: "Engineer",
    employmentType: "Internship",
    postedDate: "2026-07-15",
    summary:
      "Entry-level QA internship executing manual and automated test cases, logging defects, and monitoring QA metrics for a SaaS analytics product.",
    highlights: [
      "Execute manual and automated test cases and analyze results",
      "Write maintainable automated test scripts and help upgrade frameworks",
      "For candidates graduating 2023–2025 with a CS/engineering background",
      "Application deadline: August 31, 2026",
    ],
    skills: ["Manual Testing", "Test Automation", "Bug Tracking"],
    applyUrl:
      "https://himalayas.app/companies/drivetrain/jobs/quality-assurance-engineering-qae-intern",
    hrEmail: "careers@drivetrain.ai",
    source: "Himalayas",
  },
  {
    id: "bluepi-qa-engineer-remote",
    title: "Quality Assurance Engineer",
    company: "BluePi",
    location: "Remote (open in 15+ countries incl. India)",
    region: "Remote",
    remote: true,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-07-30",
    salary: "THB 40,000 – 60,000 / month",
    summary:
      "Remote QA role open across 15+ countries including India, designing manual and automated testing strategy and setting up CI/CD automation in GitLab.",
    highlights: [
      "Minimum 2 years as a QA Engineer, 1+ year automated testing",
      "Robot Framework, Selenium, Appium, Cypress, Postman, or JMeter",
      "Functional, non-functional, automated, and performance testing",
      "Remote with flexible hours; equipment provided, learning budget included",
    ],
    skills: ["Selenium", "Appium", "Cypress", "Postman", "JMeter", "CI/CD"],
    applyUrl: "https://himalayas.app/companies/bluepi/jobs/quality-assurance-engineer",
    source: "Himalayas",
  },
  {
    id: "miquido-qa-engineer-remote",
    title: "QA Engineer",
    company: "Miquido",
    location: "Remote (worldwide)",
    region: "Remote",
    remote: true,
    seniority: "Engineer",
    employmentType: "Full-time",
    postedDate: "2026-08-03",
    summary:
      "Mid-level QA Engineer role at Miquido, a digital product agency, open to candidates worldwide. See the original listing for full role details.",
    highlights: [
      "Open to candidates from all countries, worldwide hiring timezones",
      "Mid-level experience; QA, testing automation focus",
      "See the original posting for the complete responsibilities and requirements",
    ],
    skills: ["Software Testing", "Test Automation"],
    applyUrl: "https://himalayas.app/companies/miquido/jobs/qa-engineer",
    source: "Himalayas",
  },
  {
    id: "oxide-quality-manager-remote",
    title: "Quality Manager",
    company: "Oxide Computer Company",
    location: "Remote",
    region: "Remote",
    remote: true,
    seniority: "Manager",
    employmentType: "Full-time",
    postedDate: "2026-07-29",
    salary: "$275,000 / year",
    summary:
      "Quality Manager role at Oxide, a company building on-premises cloud computing hardware and software. Full detail available on the original listing.",
    highlights: [
      "Full-time, fully remote position",
      "See the original posting for the complete responsibilities and requirements",
    ],
    skills: ["Quality Management"],
    applyUrl: "https://to.indeed.com/aa7ggt6rtw96",
    source: "Indeed",
  },
];
