export type RecruiterCategory = "Recruiting Agency" | "IT Company";
export type HiringRegion = "Remote" | "UAE" | "India" | "Egypt";

export interface RecruiterContact {
  id: string;
  company: string;
  category: RecruiterCategory;
  hiresFor: HiringRegion[];
  location: string;
  contactType: "email" | "careers_page";
  contactValue: string;
  contactLabel?: string;
  note?: string;
}

// Every entry here was verified against the company's own site or a genuine
// job posting we sourced — never guessed. Most large corporates don't publish
// a direct recruiter email at all (application-portal only), so those are
// listed with a careers page link instead of an invented address.
export const recruiters: RecruiterContact[] = [
  // ---------- Recruiting agencies ----------
  {
    id: "michael-page-india",
    company: "Michael Page India",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Gurgaon, Mumbai, Bengaluru",
    contactType: "email",
    contactValue: "enquiries@michaelpage.co.in",
    note: "Global professional recruitment consultancy with a technology practice; Gurgaon (Delhi NCR) office.",
  },
  {
    id: "xpheno",
    company: "Xpheno",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Bengaluru (HQ), Delhi, Mumbai, Pune, Hyderabad",
    contactType: "email",
    contactValue: "hr@xpheno.com",
    note: "Specialist IT/tech staffing firm with a Delhi office.",
  },
  {
    id: "ciel-hr",
    company: "CIEL HR",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Chennai (HQ), pan-India",
    contactType: "email",
    contactValue: "info@cielhr.com",
    note: "One of India's largest HR/staffing firms across industries including IT.",
  },
  {
    id: "teamlease-digital",
    company: "TeamLease Digital",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Delhi NCR (Wazirpur) and pan-India",
    contactType: "careers_page",
    contactValue: "https://www.teamleasedigital.com/contact-us",
    note: "IT & tech staffing arm of TeamLease; no direct email published, contact form only.",
  },
  {
    id: "quess-corp",
    company: "Quess IT Staffing",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Bengaluru (HQ), pan-India",
    contactType: "careers_page",
    contactValue: "https://itstaffing.quesscorp.com/contact-us/",
    note: "One of India's largest staffing companies; contact form only, no public email.",
  },
  {
    id: "nadia-global",
    company: "NADIA Global",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai, Abu Dhabi",
    contactType: "email",
    contactValue: "contact@nadiaglobal.com",
    note: "UAE/KSA-focused executive search and permanent recruitment agency.",
  },
  {
    id: "charterhouse-middle-east",
    company: "Charterhouse Middle East",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "info@charterhouseme.ae",
    note: "Established Dubai recruitment consultancy across technology and other sectors.",
  },
  {
    id: "cooper-fitch",
    company: "Cooper Fitch",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://cooperfitch.ae/contact-us/",
    note: "Dubai executive search and recruitment firm; no public email, contact form only.",
  },
  {
    id: "kelly-services-india",
    company: "Kelly Services India",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Gurgaon",
    contactType: "email",
    contactValue: "kellyservicesindia@kellyservices.co.in",
    note: "Global staffing firm with a Gurgaon (Delhi NCR) office and dedicated IT/tech practice.",
  },
  {
    id: "manpowergroup-india",
    company: "ManpowerGroup India",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Gurgaon",
    contactType: "careers_page",
    contactValue: "https://www.manpowergroup.co.in/contact.aspx",
    note: "Global workforce solutions firm with a Gurgaon office; email is Cloudflare-obscured on their site, use the contact page.",
  },
  {
    id: "talent500",
    company: "Talent500",
    category: "Recruiting Agency",
    hiresFor: ["India", "Remote"],
    location: "Bengaluru (HQ), places India talent remotely with global companies",
    contactType: "email",
    contactValue: "growth@talent500.co",
    note: "ANSR-backed platform placing vetted Indian tech talent into remote roles at global companies.",
  },
  {
    id: "robert-walters-me",
    company: "Robert Walters Middle East",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "DIFC, Dubai",
    contactType: "email",
    contactValue: "dubai@robertwalters.com",
    note: "Global professional recruitment consultancy with a Dubai technology practice.",
  },
  {
    id: "morgan-mckinley-dubai",
    company: "Morgan McKinley",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Oud Metha, Dubai",
    contactType: "careers_page",
    contactValue: "https://www.morganmckinley.com/ae",
    note: "Global professional recruitment firm with a Dubai office; no public email verified, contact via site.",
  },
  {
    id: "adecco-middle-east",
    company: "Adecco Middle East",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai Marina, Dubai",
    contactType: "email",
    contactValue: "adeccoae.info@adecco.com",
    note: "Global workforce solutions firm with IT/professional staffing across the UAE.",
  },
  {
    id: "korn-ferry-dubai",
    company: "Korn Ferry",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "DIFC, Dubai",
    contactType: "careers_page",
    contactValue: "https://www.kornferry.com/contact",
    note: "Global executive search and organizational consulting firm; senior/leadership-tier roles. No public email, contact form only.",
  },
  {
    id: "brunel-middle-east",
    company: "Brunel Middle East",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai (regional HQ), Abu Dhabi",
    contactType: "careers_page",
    contactValue: "https://www.brunel.net/en/middle-east",
    note: "Global technical staffing firm -- but their actual specialty is Oil & Gas, Renewables, and Infrastructure, not general software QA. Worth confirming fit before reaching out.",
  },
  {
    id: "dicetek-agency",
    company: "Dicetek LLC",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Deira, Dubai · Saif Zone, Sharjah",
    contactType: "email",
    contactValue: "career@dicetekuae.com",
    note: "IT solutions and technical staffing firm placing contract testers and QA engineers, primarily banking/financial systems.",
  },
  {
    id: "net2source-uae",
    company: "Net2Source",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Sheikh Zayed Road, Dubai",
    contactType: "email",
    contactValue: "info@net2source.ae",
    note: "Global staffing firm active in UAE IT/AI recruitment; confirmed posting real QA Engineer roles via LinkedIn.",
  },
  {
    id: "salt-recruitment-dubai",
    company: "Salt Recruitment",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai Marina, Dubai",
    contactType: "careers_page",
    contactValue: "https://welovesalt.com/ae/",
    note: "Digital/tech recruitment agency; confirmed posting real fintech QA Engineer roles in Dubai. No public email, contact form only.",
  },
  {
    id: "cybotrix-technologies",
    company: "Cybotrix Technologies",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "contact@cybotrix.com",
    note: "QA-specialized recruitment agency in Dubai; explicitly focused on manual/automation testing, API testing, and performance engineering roles.",
  },
  {
    id: "hire-resolve-uae",
    company: "Hire Resolve",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai, Abu Dhabi, Sharjah and other UAE emirates",
    contactType: "careers_page",
    contactValue: "https://www.hireresolve.ae/contact-us/hire-it-professionals-now/",
    note: "20+ year UAE recruitment agency covering IT professionals; no public email, contact form only.",
  },
  {
    id: "hr-ways",
    company: "HR Ways",
    category: "Recruiting Agency",
    hiresFor: ["UAE", "Remote"],
    location: "Pakistan-based, places tech talent into UAE and remote roles",
    contactType: "careers_page",
    contactValue: "https://hrways.co/contact-us/",
    note: "Technical recruitment/HR outsourcing firm sourcing tech talent for UAE and remote software roles; no public email found.",
  },
  {
    id: "marc-ellis",
    company: "Marc Ellis",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai Silicon Oasis, Dubai",
    contactType: "email",
    contactValue: "nadja@marc-ellis.com",
    contactLabel: "IT recruitment contact (from their own job postings)",
    note: "Award-winning Dubai digital/tech recruitment agency covering banking, cloud, and IT & telecommunications.",
  },
  {
    id: "aiqu-search",
    company: "AIQU",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Sheikh Zayed Road, Dubai",
    contactType: "careers_page",
    contactValue: "https://aiqusearch.com/contact/",
    note: "IT & tech recruitment agency across the GCC; no specific public email verified, contact page only.",
  },
  {
    id: "hays-technology-uae",
    company: "Hays Technology",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai Knowledge Park, Dubai",
    contactType: "careers_page",
    contactValue: "https://www.hays.ae/it",
    note: "Global staffing firm's specialist IT/tech recruitment practice in the UAE; contact page blocks automated verification of a direct email.",
  },
  {
    id: "caliberly-agency",
    company: "Caliberly",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai World Trade Center District, Dubai",
    contactType: "careers_page",
    contactValue: "https://caliberly.com/contacts/",
    note: "Dubai recruitment agency placing both Manual and Automation QA Engineers; email is Cloudflare-obscured on their site, use the contact page.",
  },
  {
    id: "mena-recruitment",
    company: "MENA Recruitment",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Burj Khalifa District, Dubai",
    contactType: "email",
    contactValue: "info@mena-recruitment.com",
    note: "Dubai recruitment agency covering IT and other sectors across the MENA region.",
  },
  {
    id: "gulftalent-employers",
    company: "GulfTalent (Employer Services)",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.gulftalent.com/recruitment-solutions",
    note: "Leading Middle East job platform's recruiting-solutions arm for employers; phone contact only, no public email.",
  },
  {
    id: "abc-consultants",
    company: "ABC Consultants",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "New Delhi (Nehru Place) and pan-India",
    contactType: "email",
    contactValue: "client@abcconsultants.in",
    note: "One of India's oldest HR consulting/executive search firms, founded 1969; Delhi HQ.",
  },
  {
    id: "randstad-india",
    company: "Randstad India",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "Chennai (HQ), New Delhi and pan-India",
    contactType: "email",
    contactValue: "ramprasad.pinninti@randstad.in",
    contactLabel: "Named IT recruitment contact (not a general inbox)",
    note: "Global staffing firm with a dedicated Randstad Technologies practice and a New Delhi office.",
  },
  {
    id: "antal-international-delhi",
    company: "Antal International (New Delhi)",
    category: "Recruiting Agency",
    hiresFor: ["India"],
    location: "East Patel Nagar, New Delhi",
    contactType: "careers_page",
    contactValue: "https://www.antal.com/recruitment/india-newdelhi-epn",
    note: "Global recruitment network; New Delhi office email is Cloudflare-obscured on their site, use the contact page.",
  },
  {
    id: "collabera",
    company: "Collabera",
    category: "Recruiting Agency",
    hiresFor: ["India", "Remote"],
    location: "India (multiple cities) and global",
    contactType: "email",
    contactValue: "gcc.india@collabera.com",
    note: "Global staffing and talent solutions firm with a dedicated India Global Capability Centers desk.",
  },
  {
    id: "nlb-services",
    company: "NLB Services",
    category: "Recruiting Agency",
    hiresFor: ["India", "Remote"],
    location: "Alpharetta, GA (HQ) with major India operations",
    contactType: "email",
    contactValue: "info@nlbservices.com",
    note: "IT staffing and digital workforce solutions provider active across the US, India, and Europe.",
  },
  {
    id: "instahyre",
    company: "Instahyre",
    category: "Recruiting Agency",
    hiresFor: ["India", "Remote"],
    location: "New Delhi",
    contactType: "careers_page",
    contactValue: "https://www.instahyre.com/",
    note: "Delhi-headquartered tech hiring platform used by Google, Amazon, Flipkart, and others; no public email.",
  },
  {
    id: "cutshort",
    company: "Cutshort",
    category: "Recruiting Agency",
    hiresFor: ["India", "Remote"],
    location: "Pune",
    contactType: "email",
    contactValue: "hello@cutshort.io",
    note: "India tech hiring platform covering engineering, QA, product, and design roles.",
  },
  {
    id: "gun-io",
    company: "Gun.io",
    category: "Recruiting Agency",
    hiresFor: ["Remote"],
    location: "Global (remote freelance developer network)",
    contactType: "email",
    contactValue: "team@gun.io",
    note: "Connects companies with vetted freelance software developers and testers worldwide.",
  },
  {
    id: "tasc-outsourcing",
    company: "TASC Outsourcing",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "ea@tascoutsourcing.com",
    note: "18+ year UAE staffing and recruitment agency handling sourcing, payroll, and visa processing.",
  },
  {
    id: "guildhall-agency",
    company: "Guildhall",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai, with reach across Saudi Arabia and the GCC",
    contactType: "email",
    contactValue: "info@guildhall.agency",
    note: "Executive search firm with a dedicated Digital & Tech recruitment vertical.",
  },
  {
    id: "michael-page-uae",
    company: "Michael Page UAE",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "clientmiddleeast@michaelpage.ae",
    note: "UAE arm of the global Michael Page recruitment consultancy, technology practice included.",
  },
  {
    id: "kershaw-leonard",
    company: "Kershaw Leonard",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai Knowledge Park",
    contactType: "email",
    contactValue: "mike@kershawleonard.net",
    contactLabel: "Named consultant contact (not a general inbox)",
    note: "UAE/GCC HR and recruitment consultancy offering executive search and staffing.",
  },
  {
    id: "propel-consult",
    company: "Propel Consult",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Bahrain, active across GCC incl. UAE",
    contactType: "email",
    contactValue: "nada@propelconsult.com",
    contactLabel: "Named consultant contact (not a general inbox)",
    note: "GCC-wide recruitment agency covering Saudi Arabia, Bahrain, and the UAE.",
  },
  {
    id: "black-pearl-consult",
    company: "Black Pearl Consult",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "bibin@blackpearlconsult.com",
    contactLabel: "Named consultant contact (not a general inbox)",
    note: "UAE HR solutions provider offering permanent recruitment and consultancy.",
  },
  {
    id: "aspire-manpower",
    company: "ASPIRE Manpower Services",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "UAE (MOHRE-licensed)",
    contactType: "email",
    contactValue: "info@aspirems.ae",
    note: "MOHRE-licensed UAE staffing agency; stated focus is Oil & Gas, Facility Management, and Hospitality rather than IT — worth confirming QA/tech fit before reaching out.",
  },
  {
    id: "tiger-recruitment",
    company: "Tiger Recruitment",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai office (HQ London)",
    contactType: "careers_page",
    contactValue: "https://tiger-recruitment.com/offices/dubai/",
    note: "Has a Digital/Technology division, but their Dubai office emphasizes business support, HR, and finance placements — no public email, contact form only.",
  },
  {
    id: "irwin-and-dow",
    company: "Irwin & Dow",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.irwinanddow.com/",
    note: "Dubai boutique agency focused on Business Support, HR, and Finance — not an IT/tech specialist; no public email.",
  },
  {
    id: "robert-half-uae",
    company: "Robert Half UAE",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "DIFC, Dubai",
    contactType: "careers_page",
    contactValue: "https://www.roberthalf.com/ae/en",
    note: "Global staffing firm with IT recruitment in the UAE; no public general email, contact via site.",
  },
  {
    id: "toptal",
    company: "Toptal",
    category: "Recruiting Agency",
    hiresFor: ["Remote"],
    location: "Global (fully distributed)",
    contactType: "email",
    contactValue: "support@toptal.com",
    contactLabel: "Support (general — not a dedicated recruiting inbox)",
    note: "Freelance talent network placing vetted developers/QA talent with global clients remotely.",
  },
  {
    id: "turing",
    company: "Turing",
    category: "Recruiting Agency",
    hiresFor: ["Remote"],
    location: "Palo Alto, CA (matches remote talent globally)",
    contactType: "careers_page",
    contactValue: "https://www.turing.com/jobs",
    note: "Matches remote developers/QA engineers with US companies; no public email, apply via platform.",
  },

  // ---------- IT / tech companies ----------
  {
    id: "tcs",
    company: "Tata Consultancy Services (TCS)",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Pan-India incl. Delhi NCR",
    contactType: "email",
    contactValue: "careers@tcs.com",
    note: "Published recruitment contact per TCS's own careers site.",
  },
  {
    id: "newgen-software",
    company: "Newgen Software",
    category: "IT Company",
    hiresFor: ["India"],
    location: "New Delhi (Qutab Institutional Area)",
    contactType: "email",
    contactValue: "careers@newgen.co.in",
    note: "Enterprise software product company (BPM, content management) headquartered in Delhi.",
  },
  {
    id: "publicis-sapient",
    company: "Publicis Sapient",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Gurgaon",
    contactType: "email",
    contactValue: "hiring@publicissapient.com",
    note: "Digital business transformation consultancy with a large Gurgaon engineering office.",
  },
  {
    id: "nagarro",
    company: "Nagarro",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Gurugram (HQ)",
    contactType: "careers_page",
    contactValue: "https://www.nagarro.com/en/careers",
    note: "Digital engineering firm headquartered in Gurugram; no public recruiting email.",
  },
  {
    id: "coforge",
    company: "Coforge",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Greater Noida",
    contactType: "careers_page",
    contactValue: "https://careers.coforge.com/",
    note: "IT services company (formerly NIIT Technologies) with a major Noida campus; no public email.",
  },
  {
    id: "exl-service",
    company: "EXL Service",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Gurgaon",
    contactType: "careers_page",
    contactValue: "https://www.exlservice.com/careers",
    note: "Data analytics and digital operations company with a large Gurgaon office; no public email.",
  },
  {
    id: "property-finder",
    company: "Property Finder",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Dubai Media City",
    contactType: "careers_page",
    contactValue: "https://www.propertyfinder.com/careers",
    note: "Leading MENA property-tech portal headquartered in Dubai; no public recruiting email.",
  },
  {
    id: "bayut",
    company: "Bayut",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.bayut.com/careers/",
    note: "UAE's top property portal (Dubizzle Group); no public recruiting email, applications via Workable.",
  },
  {
    id: "hcltech",
    company: "HCLTech",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Noida and pan-India",
    contactType: "careers_page",
    contactValue: "https://careers.hcltech.com/",
    note: "No public recruiting email — applications go through the careers portal only.",
  },
  {
    id: "cognizant-india",
    company: "Cognizant",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Gurugram, Noida",
    contactType: "careers_page",
    contactValue: "https://careers.cognizant.com/india-en/",
    note: "No public recruiting email — applications go through the careers portal only.",
  },
  {
    id: "genpact",
    company: "Genpact",
    category: "IT Company",
    hiresFor: ["India"],
    location: "Gurugram, Noida",
    contactType: "careers_page",
    contactValue: "https://www.genpact.com/careers",
    note: "No public recruiting email — applications go through the careers portal only.",
  },
  {
    id: "talabat",
    company: "talabat",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "inquiries@talabat.com",
    contactLabel: "General inquiries (not HR-specific)",
    note: "Regional delivery-tech platform (Delivery Hero) with a large engineering org in Dubai.",
  },
  {
    id: "careem",
    company: "Careem",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.careem.com/careers/",
    note: "No public recruiting email — applications go through the careers portal only.",
  },
  {
    id: "du-eitc",
    company: "du (Emirates Integrated Telecommunications)",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Dubai, Abu Dhabi",
    contactType: "careers_page",
    contactValue: "https://www.du.ae/about/careers",
    note: "No public recruiting email — applications go through the careers portal only.",
  },
  {
    id: "g42",
    company: "G42",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Abu Dhabi",
    contactType: "careers_page",
    contactValue: "https://careers.g42.ai/",
    note: "AI/tech holding group; only a media contact is public, no HR email — apply via the careers portal.",
  },
  {
    id: "emirates-group",
    company: "The Emirates Group",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.emiratesgroupcareers.com/search-and-apply/",
    note: "No public recruiting email — applications go through the careers portal only.",
  },

  // ---------- Genuine emails surfaced directly from real job postings we sourced ----------
  {
    id: "dailypoint",
    company: "dailypoint (Toedt, Dr. Selk & Coll. GmbH)",
    category: "IT Company",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "bewerbungen@dailypoint.net",
    note: "Hotel-industry CRM company; email was published directly in their Software Tester job posting.",
  },
  {
    id: "rxcloud",
    company: "RxCloud",
    category: "IT Company",
    hiresFor: ["Remote", "India"],
    location: "India, remote",
    contactType: "email",
    contactValue: "megha.saxena@therxcloud.com",
    note: "Healthcare-tech company; email was published directly in their Automation Tester job posting.",
  },
  {
    id: "drivetrain",
    company: "Drivetrain",
    category: "IT Company",
    hiresFor: ["Remote", "India"],
    location: "India, remote",
    contactType: "email",
    contactValue: "careers@drivetrain.ai",
    note: "SaaS analytics company; email was published directly in their QA internship posting.",
  },

  // ---------- Egypt ----------
  {
    id: "talent-360-egypt",
    company: "Talent 360",
    category: "Recruiting Agency",
    hiresFor: ["Egypt"],
    location: "Nasr City, Cairo",
    contactType: "email",
    contactValue: "info@talent-360.me",
    note: "Cairo-based HR consultancy and talent acquisition partner for SMEs and startups across Egypt and Saudi Arabia; also the company behind several QA roles we sourced directly.",
  },
  {
    id: "keys-hr-recruitment-egypt",
    company: "Keys HR & Recruitment Services",
    category: "Recruiting Agency",
    hiresFor: ["Egypt"],
    location: "Cairo",
    contactType: "email",
    contactValue: "info@keysgroupservices.com",
    note: "Cairo headhunting agency specializing in tech talent acquisition, including software developers, IT, and cybersecurity roles.",
  },
  {
    id: "the-tech-talents-egypt",
    company: "THE TECH TALENTS",
    category: "Recruiting Agency",
    hiresFor: ["Egypt"],
    location: "Cairo",
    contactType: "email",
    contactValue: "careers@thetechtalents.com",
    note: "Tech-focused recruitment agency connecting developers, engineers, and IT professionals with companies across Egypt, the Gulf, and the EU.",
  },
  {
    id: "tcrutr-egypt",
    company: "tcrutr",
    category: "Recruiting Agency",
    hiresFor: ["Egypt"],
    location: "Cairo (also Riyadh)",
    contactType: "email",
    contactValue: "info@tcrutr.com",
    note: "AI-powered tech recruitment agency placing software engineers, DevOps, QA/cybersecurity, data, and cloud roles across Egypt and Saudi Arabia.",
  },
  {
    id: "trimetis-services-egypt",
    company: "Trimetis Services",
    category: "Recruiting Agency",
    hiresFor: ["Egypt"],
    location: "Cairo (HQ Austria)",
    contactType: "email",
    contactValue: "nada.sallam@trimetis.com",
    contactLabel: "Recruiter contact (from their own job posting, not a general inbox)",
    note: "Consulting and IT expert-sourcing firm building a Cairo automation-testing team; email was published directly in their Senior Automation Test Engineer posting.",
  },
  {
    id: "tawzef-egypt",
    company: "Tawzef",
    category: "Recruiting Agency",
    hiresFor: ["Egypt"],
    location: "Cairo",
    contactType: "email",
    contactValue: "info@tawzef.com",
    note: "Broad HR solutions and recruitment provider across Egypt/EMEA covering all sectors, not IT-specific — worth confirming tech/QA fit before reaching out.",
  },
  {
    id: "target-hr-solutions-egypt",
    company: "Target HR Solutions",
    category: "Recruiting Agency",
    hiresFor: ["Egypt"],
    location: "Cairo",
    contactType: "email",
    contactValue: "target@targetdhr.com",
    note: "General executive search and HR consultancy with multinational clients (Uber, Unilever, ENI); not IT-specific — worth confirming tech/QA fit before reaching out.",
  },
  {
    id: "fawry",
    company: "Fawry",
    category: "IT Company",
    hiresFor: ["Egypt"],
    location: "6th of October City, Giza",
    contactType: "careers_page",
    contactValue: "https://www.fawry.com/careers/",
    note: "Egypt's largest electronic payments network; no public recruiting email, applications go through the careers portal only.",
  },
  {
    id: "paymob",
    company: "Paymob",
    category: "IT Company",
    hiresFor: ["Egypt"],
    location: "New Maadi, Cairo",
    contactType: "careers_page",
    contactValue: "https://paymob.com/en/careers",
    note: "MENA digital payments infrastructure company headquartered in Cairo; no public recruiting email, applications go through the careers portal only.",
  },
  {
    id: "bosta",
    company: "Bosta",
    category: "IT Company",
    hiresFor: ["Egypt"],
    location: "Cairo",
    contactType: "careers_page",
    contactValue: "https://bosta.co/en-eg/careers",
    note: "Cairo-based delivery and logistics-tech platform; no public recruiting email, applications go through the careers portal only.",
  },
  {
    id: "luciq-instabug",
    company: "Luciq (formerly Instabug)",
    category: "IT Company",
    hiresFor: ["Egypt"],
    location: "Cairo/Giza",
    contactType: "careers_page",
    contactValue: "https://luciq.ai/careers",
    note: "Cairo-born mobile observability platform (rebranded from Instabug in 2025); no public recruiting email, applications go through the careers portal only.",
  },
  {
    id: "maxab",
    company: "MaxAB",
    category: "IT Company",
    hiresFor: ["Egypt"],
    location: "Cairo",
    contactType: "careers_page",
    contactValue: "https://careers.maxab.io/",
    note: "B2B food and grocery e-commerce platform serving the MENA region; no public recruiting email, applications go through the careers portal only.",
  },

  // ---------- More UAE agencies (verified individually; several emails a user-supplied list gave for these were wrong or outdated and were corrected against each company's real site) ----------
  {
    id: "edge-executive",
    company: "Edge Executive",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "HDS Tower, Dubai",
    contactType: "email",
    contactValue: "info@edgeexecutive.com",
    note: "IT, Digital & Technology recruitment specialist in Dubai.",
  },
  {
    id: "first-select",
    company: "First Select",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "info@firstselectuae.com",
    note: "Multi-sector staffing agency (part of G4S UAE) covering IT, Aviation, Banking, Engineering, and more.",
  },
  {
    id: "dawaam",
    company: "Dawaam",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Sheikh Zayed Road, Dubai",
    contactType: "email",
    contactValue: "info@dawaam.net",
    note: "Regional headhunting and staffing firm covering Finance, Engineering, Sales, and other sectors across the UAE/GCC; not IT-specific.",
  },
  {
    id: "connect-resources",
    company: "Connect Resources",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Sheikh Zayed Road, Dubai",
    contactType: "email",
    contactValue: "contact@connectresources.ae",
    note: "EOR, PEO, and staffing/workforce solutions provider; general recruitment, not IT-specific.",
  },
  {
    id: "silicon-valley-associates-recruitment",
    company: "Silicon Valley Associates Recruitment (SVA)",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai Silicon Oasis, Dubai",
    contactType: "email",
    contactValue: "marketing@svarecruitment.com",
    note: "IT and technology recruitment specialist with offices in Hong Kong, Singapore, and Dubai.",
  },
  {
    id: "gulf-recruitment-group",
    company: "The Gulf Recruitment Group",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "email",
    contactValue: "info@thegulfrecruitmentgroup.com",
    note: "Executive recruitment group specializing in Manufacturing, Legal, and HR — not IT-specific, worth confirming tech/QA fit before reaching out.",
  },
  {
    id: "accel-hr-consulting",
    company: "Accel HR Consulting",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Oud Metha, Dubai",
    contactType: "email",
    contactValue: "info@accelhrc.com",
    note: "General HR consultancy and recruitment agency in Dubai since 2013, includes IT roles among other sectors.",
  },
  {
    id: "manpowergroup-middle-east",
    company: "ManpowerGroup Middle East",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai Internet City, Dubai",
    contactType: "email",
    contactValue: "info@manpower-me.com",
    note: "Regional arm of the global ManpowerGroup staffing firm, covering IT, finance, engineering, and more across the GCC.",
  },
  {
    id: "halian-uae",
    company: "Halian",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.halian.com/en-ae/contact/website-contact-form-halian",
    note: "IT services and technology recruitment agency (software engineering, cloud, cybersecurity, data); no public email, contact form only.",
  },
  {
    id: "mackenzie-jones",
    company: "Mackenzie Jones",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Jumeirah Lake Towers, Dubai",
    contactType: "careers_page",
    contactValue: "https://www.mackenziejones.com/",
    note: "Recruitment agency covering finance, marketing, technology, and legal roles; no public email, contact via site.",
  },
  {
    id: "gulf-connexions",
    company: "Gulf Connexions",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai (also Abu Dhabi, Bahrain, Qatar)",
    contactType: "careers_page",
    contactValue: "https://www.gulfconnexions.com/",
    note: "Specialist recruitment consultancy across finance and technology; no public email, contact via site.",
  },
  {
    id: "staff-connect",
    company: "Staff Connect",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.staffconnect.ae/",
    note: "IT recruitment agency also covering healthcare, finance, and engineering across Dubai, Abu Dhabi, and Sharjah; no public email, contact via site.",
  },
  {
    id: "nathan-and-nathan",
    company: "Nathan & Nathan",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://www.nathanhr.com/",
    note: "HR outsourcing and staffing firm, including executive search; general recruitment, not IT-specific — no public email, contact via site.",
  },
  {
    id: "capstone-solutions",
    company: "Capstone Solutions",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://capstone-solutions.com/",
    note: "Recruitment and RPO provider focused on construction, MEP, and oil & gas; not IT-specific — no public email, contact via site.",
  },
  {
    id: "meethaq-employment-agency",
    company: "Meethaq Employment Agency",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "DWTC, Dubai",
    contactType: "careers_page",
    contactValue: "https://meethaq.ae/contact-us/",
    note: "Staffing and HR outsourcing provider (part of Al Ghandi Group) covering education, healthcare, and technology; no public email, contact via site.",
  },
  {
    id: "innovations-group",
    company: "Innovations Group",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Dubai",
    contactType: "careers_page",
    contactValue: "https://innovationuae.com/",
    note: "UAE HR consultancy covering general and permanent recruitment; not IT-specific — no public email, contact via site.",
  },
  {
    id: "alliance-recruitment-agency",
    company: "Alliance Recruitment Agency",
    category: "Recruiting Agency",
    hiresFor: ["UAE"],
    location: "Al Seef Tower, Dubai Marina, Dubai",
    contactType: "careers_page",
    contactValue: "https://www.alliancerecruitmentagency.ae/",
    note: "General recruitment and HR consulting agency; only a named individual's email is published rather than a general inbox, so we link to their site instead.",
  },
];
